version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html  
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - db_data:/var/lib/mysql

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  load_test:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
    command: -f /locust/locustfile.py --host=http://nginx

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    command: -nginx.scrape-uri=http://nginx/stub_status
    
  mysqld_exporter:
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      DATA_SOURCE_NAME: "test_user:test_password@(mariadb:3306)/"
    depends_on:
      - mariadb

  cadvisor:
    image: google/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
        
volumes:
  db_data:
  grafana_data: