version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html  
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nginx-exporter
      - php


  php:
    image: php:8.0-fpm
    environment:
      MYSQL_SERVER_NAME: ${MYSQL_SERVER_NAME}  
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: bash -c "docker-php-ext-install mysqli && php-fpm"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8
    restart: always
    volumes:      
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb:/var/lib/mysql
   
  

  mariadb_exporter:
    image: prom/mysqld-exporter
    environment:
    - DATA_SOURCE_NAME=${DATA_SOURCE_NAME}  
    command:
      - --config.my-cnf=/etc/mysqld_exporter/.my.cnf
      - --mysqld.address=mariadb:3306
    ports:
      - "9104:9104"
    volumes:
      - ./.my.cnf:/etc/mysqld_exporter/.my.cnf:ro
    
    depends_on:
      - mariadb 

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/var/lib/grafana/provisioning/dashboards
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'     
      - '--storage.tsdb.path=/prometheus' 
      - '--storage.tsdb.retention.time=7d' 
    restart: always
  
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"


  load_test:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/locust
    command: -f /locust/locustfile.py --host=http://nginx

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"   
    command: [ "-nginx.scrape-uri", "http://nginx/stub_status" ]
     

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.39.0
    ports:
      - "3033:8080"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

volumes:
  db_data:
  grafana_data:
  prometheus_data: