# grafana/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:   

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080'] 

  - job_name: 'mariadb_exporter'
    static_configs:
      - targets: ['mariadb_exporter:9104'] 

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
    

rule_files:
   - '/etc/prometheus/alert.rules.yml' 